### ISSUE TITLE
Prepare the Authentication Section.

### ISSUE THREAD

**Issue by Scholasticpal** [Heritians/Connecting-Villages#37]
The Login Page consists of:
- Login Pop-up Page: displays after landing on the site and interacting with it.
         1. id no.
         2. Password
         3. role: User, Admin, Owner
         4. Village  name:
         (if the owner is, the village name will blur out)

The drop-down with the following features for each Role:
- Owner: 
          1. Create Account - Admin
          6. Create Account - User
          7. View Data - All villages
          8. View Analytics - All Villages
          9. fill out the form
          10. Logout

- Admin:
          1. Create Account - User
          2. View/Modify Data  - Selected village
          3. View analytics - Selected Village
          4. fill out the form
          5. Logout

- User:
         1. fill out the form
         2. Logout

**Comment by mayureshagashe2105** [comment]
#44
