### ISSUE TITLE
Improve the frontend-documentation

### ISSUE THREAD

**Issue by Vishesht27** [Heritians/Connecting-Villages#4]
Add the tech stack used and architecture for the project and how it is making things efficient and better in a README file

**Comment by abdoachhoubi** [comment]
Hi @Vishesht27 I can help with all the docs and readme files, I can also refactor and clean code.
I'd be happy If contribute to this project!

**Comment by mayureshagashe2105** [comment]
Hi, @abdoachhoubi!
Thank you for your interest in the project. We are currently setting up the basic repository workflow paradigms. Contributions are welcome after the baseline code is pushed to the repo. We hope to see you around that time. Do keep an eye on the project development. Once again, thank you for your interest!
