### ISSUE TITLE
Responsiveness of website

### ISSUE THREAD

**Issue by Scholasticpal** [Heritians/Connecting-Villages#70]
Responsiveness 

- [ ] Navbar is to be made responsive (reduce screen width and check again) and check hamburger menu
- [ ] Lock screen rotation in only portrait mode: can refer https://www.npmjs.com/package/react-screen-orientation
- [ ] form tables responsiveness

other (Optional)
- [ ] change the font color of inspiration quotes images to purple (since white is not visible on the phone)

**Comment by Scholasticpal** [comment]
Hey @Vaibhav-shrivastav !
Sure, I am assigning this issue to you.

**Comment by Vaibhav-shrivastav** [comment]
@Scholasticpal Whom should I contact to get my login credentials created at the backend ?

**Comment by Scholasticpal** [comment]
@mayureshagashe2105 and @HemanthSai7 please provide test creds to @Vaibhav-shrivastav

**Comment by mayureshagashe2105** [comment]
@Vaibhav-shrivastav, thank you for your interest. I would like to discuss a few points about your prospective contributions before you break in, it would be better if we could continue this conversation over email. Our team will be contacting you soon. Thank you.

**Comment by Vaibhav-shrivastav** [comment]
Sure! @mayureshagashe2105
